version: '3'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27107:27107"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpass
